### PR TITLE
Uses .hidden instead of v-show. Fixes #391

### LINKED ISSUE #391: Component is failing during Server side rendering
When using [vue-server-renderer](https://www.npmjs.com/package/vue-server-renderer), the rendering process fails with a `TypeError: getVShowDirective`.

### PR DESCRIPTION
**Pull request by mykeels**
Makes use of a .hidden class, instead of the v-show directive, which breaks SSR

### CODE REVIEW

**Comment by csharad** [comment]
I also had submitted the pull request for the same issue but learning from this one, mine was flawed. I didn't know the implications of `v-show`. And I used your branch in my project which is working fine but for a few issues. 

I am using nuxt and on the initial render `document is not defined` is thrown, which after refresh it goes away. Also, for a few refreshes the plain content appears for a brief moment as I think CSS is not loaded.

**Comment by mykeels** [comment]
@csharad I think the `document is not defined` error is related to this issue https://github.com/charliekassel/vuejs-datepicker/issues/393

**Comment by csharad** [comment]
@mykeels I saw you rolled back the document() abstractions. Wouldn't it be a solution to the document not being defined.

**Comment by mykeels** [comment]
I hoped it would @csharad, but there was no apparent change when I rolled-back, and I couldn't think of a way to test that it was necessary. Can you reproduce the issue?

**Comment by csharad** [comment]
Feature gating `document` didn't work. It still threw `document is not defined`. I checked the built file and found that `vue-style-loader` required `target: 'node'` in webpack to be built for SSR.

**Comment by charliekassel** [comment]
Hi @mykeels - I inadvertently merged this.
Happy to merge but I'm using yarn for this project to can you remove the `package-lock.json` and add the server renderer package using yarn so we maintain one lock file.

**Pull request merged**
