### PR TITLE
Support for translation reactive

### PR DESCRIPTION
**Pull request by vip30**
Move the translation to be computed properties for supporting reactive translation
Make the datepicker width bigger for avoiding overlap in chinese language

### CODE REVIEW

**Comment by coderdiaz** [comment]
Nice contribution 👍

**Comment by charliekassel** [comment]
Hi @vip30 

Thanks for your contribution! Happy to merge the translations to computed property but the width is a personal preference.

If you remake the PR without the width change, we can look at how to make the width easier to alter for end users.

**Comment by vip30** [comment]
@charliekassel 
I have changed back the width to 300px and agree to make the width flexible.
Because I think this problem will be occurred in the other languages

**Comment by charliekassel** [comment]
Released in v0.4.28

I think you can handle the datepicker width using css and the wrapperClass property

**Pull request merged**
