### PR TITLE
dont propagate clicks

### PR DESCRIPTION
**Pull request by adrum**
Click the nav buttons on various pickers would close the picker. This adds `preventDefault` and `stopPropagation` to those buttons.

### CODE REVIEW

**Comment by charliekassel** [comment]
Hi, I'm not seeing this behaviour.
Can you give your version and markup please.

**Comment by adrum** [comment]
Here's the markup. I saw [somewhere else](https://github.com/charliekassel/vuejs-datepicker/issues/292#issuecomment-364580582) someone noticed this behavior when it's wrapper in a label. If you can't reproduce it with this markup, I'll try to come up with a more complete example.

```
<label class="text label half">
    <span class="field-label">Start Date</span>
    <div class="field-wrapper">
        <vuejs-datepicker name="start_date" v-model="start_date" v-validate="'required'" :class="{'input': true, 'error': errors.has('start_date') }"></vuejs-datepicker>
        <span v-show="errors.has('start_date')" class="error">{{ errors.first('start_date') }}</span>
    </div>
</label>
```

**Comment by charliekassel** [comment]
This prevents the picker closing when you select a date.

**Comment by stevenharman** [comment]
@charliekassel here's a stripped down example, modified from the live demo: https://codesandbox.io/s/lpm4j270k9?module=%2Fcomponents%2FDemo.vue

**Pull request closed without merging**
