### PR TITLE
fix: cleared input on blur #489

### PR DESCRIPTION
**Pull request by yyuurreecc5**

### CODE REVIEW

**Comment by yyuurreecc5** [comment]
Fix problev when input value cleared on blur when props typeable=true

**Comment by charliekassel** [comment]
What are you trying to achieve here?
I want the input to be cleared if the typed date does not parse to a js Date.

**Comment by yyuurreecc5** [comment]
In your case, the input is always cleared on blur when typeable=true, regardless of whether the input was parsing to a js Date or not.

**Comment by charliekassel** [comment]
Ah yes you're correct.

**Comment by charliekassel** [comment]
released in v1.2.2 - thanks!

**Pull request merged**
