### PR TITLE
Date range functionality (A -> B)

### PR DESCRIPTION
**Pull request by BlitZz96**
Had the need to select a range from date A -> date B, therefore I created a simple range prop.

`<datepicker :range="true"  v-model="exampleRange" placeholder="Select range"></datepicker>`

This prop modifies some of the core functionality of the datepicker;

- The picker is not closed on selection (like inline)
- the picker lets user select two dates, one start and one end date.
- When range prop is true, the picker's input emits an object instead of date: 
`{ "from": "2018-06-07T21:55:00.000Z", "to": "2018-06-15T21:55:00.000Z" }`
- Input field value is updated with two dates: `07 - 15 Jun` (or `01 Jan - 01 Feb` if the months are not the same)
- `:format` prop formats both dates instead of default "selectedDate"
- I modified the highlighted prop to allow for visualisation of the selected dates

Todo; Would consider adding an `@mouseover` event that automatically highlights the dates? I will most likely implement this for myself in the future, but too lazy now as this suits my needs and deadline per now.

Linter is ok but I'm not too familiar with unit testing, therefore I have not created nor runned any tests.

Cheers for an awesome package 🥂

### CODE REVIEW

**Comment by charliekassel** [comment]
Hi, thanks for this contribution - I really like the idea of this but it will need some work, especially on the test coverage.
I don't have time right now to go through your changes but I wanted to add a note to say that I like where you're going with it - I'll get back to you next week some time.

PS. we don't include build files in the repo.

**Comment by BlitZz96** [comment]
> PS. we don't include build files in the repo.

Yeah, I suppose that makes sense! I'm new to this approach, how does it then build the files needed for  import?

**Comment by charliekassel** [comment]
So that's done in a `prepublish` hook just before publishing to npm - the distribution files only go to the npm registry. This keeps them out of the repo and more importantly the git diffs.
https://github.com/charliekassel/vuejs-datepicker/blob/master/package.json#L33

**Comment by BlitZz96** [comment]
Interesting! I agree regarding the git diffs, I'm sorry if I pollute your channel here, but in order for me to use my fork as "npm package" in my project, I have to include the build files.(?)

I could make another repo just for that and only merge in changes if you would like me to do that. the 4,371+ changes is annoying..

**Comment by IvoPereira** [comment]
This deserves some attention as it is worth-a-look feature for sure.

Is it stable to use your version @BlitZz96?

**Comment by BlitZz96** [comment]
My version is not merged with the newest release by instance. However, it's ~ 97% stable i would say. the 3% would be smaller bugs I have yet to reproduce. I have moved away from vuejs-datepicker due to the missing range functionalities. Don't get me wrong, my version does the job. However, the other package I came across did all of these things plus much more. Therefore I had to leave this datepicker behind for this time 😞 @IvoPereira

**Comment by AndreasHerss** [comment]
@BlitZz96 Would you mind telling what you used instead? Though i am really reluctant about dropping the vuejs-datepicker, but i could really use a range picker, instead of using 2 datepickers :)

**Comment by BlitZz96** [comment]
@AndreasHerss I used [v-calendar](https://github.com/nathanreyes/v-calendar). It also comes with a date-picker that supports singe, multiple and range dates.

**Comment by BlitZz96** [comment]
I'm closing this PR. I assume there will be no work on it, especially not from my part.

**Comment by vesper8** [comment]
@charliekassel This is a really needed feature and this PR accomplished 90% of the work.. I too am probably going to move to v-calendar because this feature is missing.. but that's too bad because here it is almost ready to be merged.. hope you add it in please!

**Pull request closed without merging**
