### PR TITLE
add today button

### PR DESCRIPTION
**Pull request by rpemberton**
I thought this would be a useful option. For those that don't want to check what today's date is.

### CODE REVIEW

**Comment by charliekassel** [comment]
Thanks for your contribution @rpemberton - I feel that this button should be near the other navigational features - i.e near the top. Also maybe useful if it's available to the month and year calendars too.

**Comment by rpemberton** [comment]
Yeh good call. I'll make those edits and let you know.

**Comment by rpemberton** [comment]
Hi Charlie, I've made those changes you suggested

**Comment by rpemberton** [comment]
@charliekassel if any more changes are required (besides merge conflicts), could you let me know?Otherwise, let's delete this one.

**Comment by rpemberton** [comment]
Closing due to inactivity

**Pull request closed without merging**
