### PR TITLE
Code cleaning

### PR DESCRIPTION
**Pull request by snovakovic**
* Remove unnecessary defaults from properties. (if property is Boolean by default it's false no need to set false as default)
* Remove unnecessary comments (the one that are not saying anything)
* Remove empty line between methods to be consistent as some methods have empty line and some not (now there is no empty lines)

### CODE REVIEW

**Comment by charliekassel** [comment]
Why remove the docblocks? What are you possibly gaining here?
Obviously with javascript you can pass anything as an argument, but having these `@params` at least part documents the code.
I can't see the point in removing comments and whitespace from the source when webpack is going remove these for us to create the bundle

**Comment by snovakovic** [comment]
> Why remove the docblocks? What are you possibly gaining here?

1) My personal taste but I believe that removed dockblock does not give any value to the code they just add nose to code making it harder to read and understand. For example there is method isDisabledMonth. it's pretty clear what that method do so I don't see point in having 5 line of comment saying just 'Whether a month is disabled' as that is very obvious from name of the month. 

2) Consistency. some of them have dockblock some not. I believe code should be as consistent as possible meaning all  methods should eather have dockblock or none of them (with exception for when dockblock are very useful and in case of removed dockblock they are not useful at all )

3) Some of them are wrong e.g isSelectedYear have this dockblock 'Whether a month is disabled'. which is clearly wrong.


> but having these @params at least part documents the code.

Everything is still same and documented it's just shorter now. We still have list of params with type nothing changed there. Only thing that is removed is default value as it's unnecessary because value by default is that value so I don't see point in explicitly saying default: false when it is already by default false. 

> I can't see the point in removing comments and whitespace

whitepsace are removed only because consistency (consistent code is good code). Because some of methods have new line and some doesn't so we should eather have new line after each method or not have new line after each method. Now we have mixed of both.

**Comment by snovakovic** [comment]
@charliekassel I have readd codeblocks so you can take a look again. The one that was wrong have now been fixed.

**Comment by charliekassel** [comment]
Great - thank you @snovakovic!

**Pull request merged**
