### PR TITLE
Implemented inline mode and updated demos accordingly

### PR DESCRIPTION
**Pull request by kkomelin**
Hi,

Thank your for your project. It looks simpler than others, so I decided to use it in my project.
I just missed the inline mode, which is implemented in this PR.

The proposed changes allow to set :inline attribute to the datepicker component in the following way:
`<datepicker :inline="true"></datepicker>`

Here is how it looks: https://imgur.com/a/rPZ6J

Please review.

Thanks,
Konstantin

### CODE REVIEW

**Comment by charliekassel** [comment]
A useful feature! Thanks

**Comment by kkomelin** [comment]
Thank you @charliekassel for reviewing and merging my PR!

**Comment by kkomelin** [comment]
@charliekassel Could you please create a new release, so that I can use in my project through npm install?

**Comment by charliekassel** [comment]
I can and will but am tied up at the moment without a computer. For the time being you can npm install from the git url if that helps

**Comment by kkomelin** [comment]
Okay, thanks.

**Pull request merged**
