### PR TITLE
Add ref

### PR DESCRIPTION
**Pull request by oknemi**
This is intended to custom focus on input element by ref.

### CODE REVIEW

**Comment by charliekassel** [comment]
Not sure why this is needed as a prop @oknemi?
`ref` can be added when adding the component to the DOM.
```
<datepicker ref="mypicker"/>
```

**Comment by oknemi** [comment]
Hi, @charliekassel. I want to make it clear, that for me it is useful when calendar shows on focus. I hope https://github.com/charliekassel/vuejs-datepicker/pull/210 will be merged one day. 

It can be useful when you need to focus on input. It doesn't work if I add ref attribute directly to the component, as you suggested. Because there's no focus function. So, in such case, I need to go throw all children elements and find input element.

**Comment by pokhrimenko** [comment]
@Eduruiz I made separate input and datepicker with inline="true". Then I made my custom wrapper for input and datepicker calendar, like dropdown. So then you can open(toggle) your dropdown with calendar by event on your custom input.

**Comment by oknemi** [comment]
@Eduruiz I made separate input and datepicker with inline="true". Then I made my custom wrapper for input and datepicker calendar, like dropdown. So then you can open(toggle) your dropdown with calendar by event on your custom input.

**Comment by Eduruiz** [comment]
@oknemi thanks!! I'll try it next time I run into this. For this project, I have been forced to change my datepicker component. "/

**Pull request merged**
