### PR TITLE
Add calendar-width property

### PR DESCRIPTION
**Pull request by enkhalifapro**

### CODE REVIEW

**Comment by charliekassel** [comment]
Hi thanks for the PR - I'm happy to accept a width prop for the calendar but you've also included a load of formatting changes to the component that I'd prefer not to have - I can't see clearly what you have added or removed because of them.
You've also included your package.json and package-lock.json file - I prefer to keep myself as the author ;) and I'm using yarn to maintain the lock file for this package.

**Comment by enkhalifapro** [comment]
Thanks @charliekassel 
it's ok done

**Comment by charliekassel** [comment]
Sorry that's not done - look at the diff in the Datepicker.vue file - almost every line has changed because you've either formatted it differently or your ide/text editor has automatically changed it.
Also the package.json has changed to using 4 spaces instead of two - which has changed every line in the file. You don't even need to include that in the PR.

**Comment by charliekassel** [comment]
You maybe best off just remaking the PR only including the things that actually change for the width prop.

**Comment by charliekassel** [comment]
I'm going to close this PR as there's too many changes in the diff - but as I mentioned above I think there's a valid case for this so feel free to open another PR only including the things that need to change.

**Pull request closed without merging**
