### PR TITLE
Add `initial-view` prop to allow picking a date by its year or month first

### PR DESCRIPTION
**Pull request by mismith**
Implements #159

### CODE REVIEW

**Comment by mismith** [comment]
Cool, thanks for fixing those up!

I've not written many tests before and didn't see that pattern used elsewhere in the specs (of defining a new component per `it()`), so I (mistakenly) opted to go with something like what was already in there instead :S

I'm curious, is that what's causing the Travis and Coveralls checks to fail too?

**Comment by mismith** [comment]
Also, while I was running the tests I got the following failure: 
```1) should allow value to be changed outside of component
     Datepicker.vue set by string
     AssertionError: expected '2016-03-14' to equal '2016-03-15' (/Users/murraysmith/Sites/vuejs-datepicker/node_modules/chai/chai.js:210)```

I think it's unrelated but figured I'd bring it to your attention to investigate if you see fit. (Timezone issues? I'm in MST w/ DST)

**Comment by charliekassel** [comment]
The travis build fails because the assertion expects false but the result is true as it states in the log, but as the nextTick is async the test completed before that resolved so it passed.

Re: Date fail - yes that's definitely timezone difference. I don't see this as I'm in GMT which is only one hour from UTC. Some day I will update these tests...

**Comment by mismith** [comment]
Ah, gotcha. Thanks for all your help

**Comment by charliekassel** [comment]
Available from `v0.7.14`

**Pull request merged**
