### PR TITLE
Add disabled-picker property to enable a full disabled state on component

### PR DESCRIPTION
**Pull request by pflirae**
The property disabled-picker has been added to enable a full component disabled state.

The property is of type Boolean and has a default of false, when ser to true the input field inside the component get disabled, and as a consecuense of that the mouse click stops working, so the component get into a read only mode, until the property gets back to true, that reenables the input field and the date can be changed angain.

Hope this simple functionality can be merged soon, since it has been comented by some others and is very usefull for read only situations.

### CODE REVIEW

**Comment by charliekassel** [comment]
Hey thanks for the PR!
I believe not having the disabled attribute at all is preferable to disabled=false
Not sure what the best way to achieve that is?

**Comment by pflirae** [comment]
Since the disabled attribute is conditioned to a property of the vue component, if the propertie has false value, when the final html is rendered the attribute disabled is not present on the html generated. The disabled attribute only shows up on the final html when the property is true. Doing this ways the disabled condition gets a reactive behavior, that is what I expect from a Vue component.

**Comment by charliekassel** [comment]
This does indeed work as expected.
Can you please document this behaviour in the available props section in the readme? Then I'm happy to merge and release this.

**Comment by pflirae** [comment]
Props section updated on readme.

**Comment by charliekassel** [comment]
Available from vuejs-datepicker@0.7.2

**Pull request merged**
