### PR TITLE
Add Arabic language support

### PR DESCRIPTION
**Pull request by mrg0lden**
Hello, I just added Arabic language support.

### CODE REVIEW

**Comment by charliekassel** [comment]
Great, thank you!

Can you please add to the readme of available languages?

**Comment by mrg0lden** [comment]
Sure, my pleasure to do that.

**Comment by charliekassel** [comment]
Hi @mrg0lden - happy to merge this, but please can you add a commit to this branch for the readme

**Comment by mrg0lden** [comment]
@charliekassel Sure! :)

**Comment by mrg0lden** [comment]
I did it!

**Comment by charliekassel** [comment]
Well done! Thanks very much.

**Pull request merged**
