### PR TITLE
Use @focus event to open calendar, use @blur to close.

### PR DESCRIPTION
**Pull request by MichMich**
This PR changes the @click event to the @Focus event of the input field to open the date picker.

With this change, the following behaviour is accomplished: when someone Tabs trough a form which includes a date picker, the date picker will open on focus to show the user it has to select a date.

For more info see #181 and #189.

The `@blur="close"` issue is solved by checking _why_ we lose focus. This is done by checking if `e.relatedTarget` is set. If so, we are losing focus because we switch focus to an other field. If we're losing focus because we click i.e. on the next month button, `e.relatedTarget` is `null`.

### CODE REVIEW

**Comment by MichMich** [comment]
Weird. It says it has a conflict, while I just rebased the repro. Can you see what the conflict is? (Or easily resolve it?)

**Comment by charliekassel** [comment]
The file structure has changed - it is now `src/components/Datepicker.vue`
But did you read my comment when I closed you last PR?
https://github.com/charliekassel/vuejs-datepicker/pull/189

tdlr: Problem is the picker does not close when you blur

**Comment by MichMich** [comment]
The blur problem is fixed (or should be fixed) in this version. Did you give it a try? If this solves the issue for you I'll try to change the PR so that it matches the current file structure.

**Comment by jam3sn** [comment]
Hey, not to pester or anything, but will this be something that gets added to the main release soon?

Thanks :)

**Comment by charliekassel** [comment]
I haven't tested it because it has conflicts.

**Comment by rtheunissen** [comment]
@MichMich can you please resolve the conflicts here?

**Comment by djzara** [comment]
I just got done implementing this exact feature on my own, but it would be nice to have it baked in so I don't have to dance around things. Anything I can do to help here?

**Comment by charliekassel** [comment]
Can we see your implementation @djzara ?

**Comment by djzara** [comment]
@charliekassel It's a hack, so I really wouldn't call it something worth sharing. Basically it involves toggling inline mode based on some event, and in this case the input field you've bound it to. If you'd like me to provide that implementation in a gist I'd be happy to.

**Pull request closed without merging**
