### PR TITLE
fix bootstrapStyling for Bootstrap 4.0.0-beta.3

### PR DESCRIPTION
**Pull request by dmocho**
Bootstrap 4.0.0-beta.3 has broken the layout used by bootstrapStyling - this commit fixes the issue.

### CODE REVIEW

**Comment by bullenb** [comment]
Bootstrap 4 stable has now been released and this change is essential to fix the input layout.

**Comment by charliekassel** [comment]
Is this change backwards compatible with bootstrap 3.x?

**Comment by dmocho** [comment]
No. Just like Bootstrap 4.0 is not compatible with Bootstrap 3.x.

**Comment by andgith** [comment]
Maybe a bootstrap-styling and a bootstrap4-styling option?

**Comment by RomeroMsk** [comment]
Any news on this? Actually, the Bootstrap 4 support can be added with #442.

**Comment by charliekassel** [comment]
Happy to see this PR updated for bootstrap 4 @dmocho if you have time?

**Pull request closed without merging**
