### PR TITLE
Made full bootstrap styling possible + added calendar button

### PR DESCRIPTION
**Pull request by websmurf**
Hi Charlie

Thanks for the addon, we are using Bootstrap and are running into a few issues with the output of the component. Don't know if you are open for it, but these modifications makes bootstrap styling possible and adds the following features:

- calendar button that activates the calendar
- possibility to use icons (font awsome or glyphicons) in the buttons (calendar + clear)

Usage would be:

`<datepicker format="D dsu MMM yyyy" :bootstrap-styling="true" :calendar-button="true" :clear-button="true" calendar-button-icon="fa fa-calendar" clear-button-icon="fa fa-times"></datepicker>`

or for glyphicon
`<datepicker format="D dsu MMM yyyy" :bootstrap-styling="true" :calendar-button="true" :clear-button="true" calendar-button-icon="glyphicon glyphicon-calendar" clear-button-icon="glyphicon glyphicon-remove"></datepicker>`

Cheers Adam

### CODE REVIEW

**Comment by charliekassel** [comment]
Hi @websmurf - thank you for this.

I'm not the biggest bootstrap fan in the world and this PR seems to hard tie the markup to bootstrap land.

However I'm willing to leave this PR open to see what reaction we get from other users.

**Comment by websmurf** [comment]
Hi Charlie

Yeah I'm afraid that you would say that ;-)

Tried to keep the output of the component as much similar to what is was before, the .input-group div is required to make the output correct unfortunately, the other stuff is optional and will work regardless of bootstrap or not

I'll let it up to you to see what you'll do with this PR

**Comment by charliekassel** [comment]
suppose you could `v-if="bootstrapped"` the .input-group div or wrap that el in a template tag or something?

**Comment by websmurf** [comment]
@charliekassel since it's a parent container, adding a v-if will hide the entire block unfortunately. 
When I add a template element, I get this error: 
`Only one <script> or <template> tag is allowed inside a Vue component.`

Best I can do is only append the classes if bootstrapStyling is set to true, unfortunately, that will still add an empty <div> element extra compared to the current output to wrap the input. Don't know if that's acceptable?

**Comment by websmurf** [comment]
No, wait, I think I can find another solution.. 
Let me try that.

**Comment by websmurf** [comment]
Ah no, that won't work because of the day/week/month view that's inside the same diff, resulting in wrong css styling

**Comment by websmurf** [comment]
An easy way to check both scenario's would be to replace the current content of index.html to:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Vue.js Datepicker</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  </head>
  <body>
    <div class="col-3">
      <br />
      <datepicker format="D dsu MMM yyyy" :bootstrap-styling="true" :calendar-button="true" :clear-button="true"></datepicker>
    </div>
    <div class="col-3">
      <br />
      <datepicker format="D dsu MMM yyyy"></datepicker>
    </div>
    <script src="dist/build.js"></script>
  </body>
</html>
```

**Comment by garygreen** [comment]
As much as I like bootstrap, I agree this does tie it very much into "bootstrap land" -- it's pretty simple to wrap the datepicker into bootstrap as it is now, no?

**Comment by erhansaydam** [comment]
Hi Charlie,
We are using bootstrap 4 in our projects and it would be very useful if this component can be styled with bootstrap. Or Can you show me the true way of customizing it. I changed the css stylings in vue file under src folder but nothing changed because but I don't know how to render the build.js file from this point.

Thank you, best regards...

**Comment by KoMiToRaY** [comment]
Hi Charlie,
We are using bootstrap 4 in our project and i want to know how do you do to stylise the datepicker with bootstrap option.

Thx

**Comment by charliekassel** [comment]
Hi @websmurf 

Ok, I am happy to go with this.
It's been a while now though and the datepicker has moved on a bit, can you pull master and adapt your changes?

**Comment by websmurf** [comment]
Jep, will try to find some time later this week :-)

**Comment by websmurf** [comment]
that should be all!

**Comment by charliekassel** [comment]
Thanks Adam!

**Pull request merged**
