### PR TITLE
Adds options to disable and highlight dates using fuctions

### PR DESCRIPTION
**Pull request by vijayanandnandam**
Implements feature request #321
example usage 
```
highlighted: {
        customPredictor: function(date) {
          // highlights the date if it is a multiple of 4
          if(date.getDate() % 4 == 0){
            return true
          }
        }
    }
```

```
disabled: {
        customPredictor: function(date) {
          // disables the date if it is a multiple of 5
          if(date.getDate() % 5 == 0){
            return true
          }
        }
    }
```

### CODE REVIEW

**Comment by vijayanandnandam** [comment]
@charliekassel any updates on this pr?

**Comment by vijayanandnandam** [comment]
thanks @charliekassel

**Comment by vijayanandnandam** [comment]
And thanks for this great library. We are using this in our project and all changes I have submitted here are used in the project 👍

**Comment by charliekassel** [comment]
Available from v0.9.18

**Comment by Glidias** [comment]
Be warned that customPredictor is not reactive even if you link it to an existing method on your Vue instance. A hackish way to go about this is to manually watch for dependant properties yourselves (or watch a computed value on the VUe with the necessary bundled dependants), and set `customPredicator = null` at first temporarily, then `Vue.nextTick( this.someFunctionToResetItBack )` to reset it back again, to force a refresh with the customPredictor since it detected the change from `null` back to the original method.

**Pull request merged**
