### PR TITLE
Provide prepend and append slots for custom content

### PR DESCRIPTION
**Pull request by tochoromero**
Sometimes you need to show custom content before or after the `input` element. 
For such cases, I have added two named slots: `prepend` and `append`.

They are necessary if you want to use bootstrap's `input-group-prepend` and `input-group-append` to show custom text or buttons.

### CODE REVIEW

**Comment by douglasryanadams** [comment]
It seems this PR fixes an error in the documentation which references functionality like this but doesn't actually implement it. Any idea when this will be merged? Anything I can do to help accelerate that?

**Comment by charliekassel** [comment]
This was before quite a big refactor, so unfortunately has conflicts as you can see.

**Comment by charliekassel** [comment]
Hi @tochoromero - can you update this PR to resolve the conflicts please?

**Comment by tochoromero** [comment]
I have created a new pull request (#620) to add the missing beforeDateInput slot.

**Pull request closed without merging**
