### PR TITLE
Add vi locale

### PR DESCRIPTION
**Pull request by imcvampire**

### CODE REVIEW

**Comment by charliekassel** [comment]
Hey @imcvampire this PR breaks the build. Can you look at it again please?

**Comment by imcvampire** [comment]
@charliekassel I just fixed it. Can you review my MR.

**Comment by charliekassel** [comment]
Great, thanks! Do you want to add it to the available languages in the readme?

**Comment by imcvampire** [comment]
Of course yes. Thank you for very nice plugin.

**Comment by imcvampire** [comment]
Moreover, I want to upgrade your plugin to compatible with vuejs 2. But I don't know do you mind if I do it?

**Comment by charliekassel** [comment]
Unfortunately my organisation where I'm using this component is not yet ready for 2.0 so I can't make the change yet.

From a compatibility check using vue-migration-helper I believe all that will be needed is to switch the ready() hook for mounted() - I think I've changed everything else to make it compatible.

**Comment by imcvampire** [comment]
I find you use `.sync` in your `v-bind`. 

So do you mind if I fork your repo and create a version for Vuejs 2.0 ?

**Comment by charliekassel** [comment]
`.sync` is not used in the component - only in the readme documentation

**Comment by charliekassel** [comment]
Why did you close @imcvampire ?

**Comment by imcvampire** [comment]
Ops. My internet just has some problem and I do a wrong click!!! I'm sorry.

About `.sync` what I mean that you don't provide any others way to do that. I want to talk about somethings like `$emit` (http://vuejs.org/api/#vm-emit)

**Comment by charliekassel** [comment]
I can probably do a direct swap with $dispatch and $emit.
I will test and if so I'll make the change.

**Pull request merged**
