### PR TITLE
Add class to input

### PR DESCRIPTION
**Pull request by renatomaric**
Now you can use `<datepicker class="form-control"></datepicker>` to add class to input: `<input readonly="" class="form-control" type="text">`

### CODE REVIEW

**Comment by renatomaric** [comment]
>@charliekassel: For the class, maybe it's better to put on the div.datepicker element so everything can be styled insider it to user preferences. This would solve #43

I had no issue with custom styling datepicker with .datepicker class, ex.:
```
<style type="text/css">
      .datepicker input {
        background-color: red;
      }
  </style>
```

This PR is intended when they using CSS framework (in my case Bootstrap) and only need to add framework's class.

**Comment by charliekassel** [comment]
Thanks @renatomaric I'll add the wrapper class prop myself.

Btw, this PR still contains https://github.com/renatomaric/vuejs-datepicker/commit/e872d888e20335599344d3b59afbe4178676c6c1#diff-46c30fb1bb2204a43024aab1429808eb

**Comment by vanderlin** [comment]
can this merge in...

**Comment by charliekassel** [comment]
I've added support for this in c8d29bf

**Comment by darkphenyx2021** [comment]
So after messing with this for a bit a good example of how to style your input is:
````
<div class="col-md-4">
         <div class="form-group">
              <label>Start Date:</label>
              <datepicker v-model="startDate" input-class="form-control"></datepicker>
        </div>
</div>
````

**Pull request closed without merging**
