### PR TITLE
Added a screenshot of the date picker

### PR DESCRIPTION
**Pull request by kkomelin**
Continued making the project marketing-friendly )

### CODE REVIEW

**Comment by charliekassel** [comment]
Great thanks @kkomelin 
Maybe the image should be in an `/imgs` or `/assets/` directory?

**Comment by kkomelin** [comment]
@charliekassel I thought that /imgs and /assets are for the assets, which are used in the component. However, if you think it is better to move it I will do it.

**Comment by charliekassel** [comment]
Yes, I can see there could be some confusion there.
I just though that cluttering the root space with files is a bit messy. I've not added a screenshot to a repo so not sure what best practice here is :/

**Comment by charliekassel** [comment]
OK @kkomelin how about a `/screenshots` dir?

**Comment by kkomelin** [comment]
Honestly, I have taken an example from:
https://github.com/hilongjw/vue-datepicker
https://github.com/Haixing-Hu/vue-datetime-picker

**Comment by charliekassel** [comment]
@kkomelin I think putting them in `/screenshots' makes the most sense to me.
It's obvious what they are and clearly not part of the component.
Plus, if we ever want any more images for the repo they can be added into the dir.

**Comment by kkomelin** [comment]
@charliekassel Agreed. I'll do it

**Comment by kkomelin** [comment]
Just a sec. Not yet done.

**Comment by kkomelin** [comment]
@charliekassel Done. Please review.

**Comment by charliekassel** [comment]
Thanks @kkomelin !

**Comment by kkomelin** [comment]
@charliekassel My pleasure

**Pull request merged**
