### PR TITLE
Add korean language to translations

### PR DESCRIPTION
**Pull request by seongmo**

### CODE REVIEW

**Comment by charliekassel** [comment]
Hi, thanks for the addition.

Can you please add this to the list of available languages in the readme file.

**Comment by charliekassel** [comment]
Looks like you are missing a closing brace

**Comment by seongmo** [comment]
Oh.. my bad. I fix it. thanks

**Comment by charliekassel** [comment]
Sorry - several PR's today on the DateLanguages.js file so last merge has now caused conflict with yours - can you please pull master again and fix conflict.
Thanks!

**Comment by seongmo** [comment]
Sure. :)

**Pull request closed without merging**
